import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';

const script = readFileSync('resources/windows/support/verify-bundled-aioncore-install.ps1', 'utf8');

describe('Windows bundled aioncore install verifier', () => {
  it('checks the Codex ACP platform binary path generated by aioncore', () => {
    expect(script).toContain('"win32-x64" { "x86_64-pc-windows-msvc" }');
    expect(script).toContain('"win32-arm64" { "aarch64-pc-windows-msvc" }');
    expect(script).toContain('node_modules\\@openai\\codex-$RuntimeKey\\vendor\\$vendorTriple\\bin\\codex.exe');
  });

  it('does not check the legacy Zed Codex ACP package layout', () => {
    expect(script).not.toContain('node_modules\\@zed-industries\\codex-acp-$RuntimeKey\\bin\\codex-acp.exe');
  });
});
